[workspace]
channels = ["conda-forge", "bioconda"]
name = "AllSTAAR"
platforms = ["linux-64"]

[tasks]

[dependencies]
bioconductor-gdsfmt = ">=1.42.0,<2"
bioconductor-genesis = ">=2.36.0,<3"
bioconductor-genomicfeatures = ">=1.58.0,<2"
bioconductor-seqarray = ">=1.46.0,<2"
bioconductor-seqvartools = ">=1.44.0,<2"
"bioconductor-txdb.hsapiens.ucsc.hg38.knowngene" = ">=3.20.0,<4"
blas = { version = "*", build = "*mkl*" }
r-compquadform = ">=1.4.4,<2"
"r-data.table" = ">=1.17.6,<2"
r-dplyr = ">=1.1.4,<2"
r-expm = ">=1.0_0,<2"
r-foreach = ">=1.5.2,<2"
r-kinship2 = ">=1.9.6.1,<2"
r-lattice = ">=0.22_7,<0.23"
r-mass = ">=7.3_64,<8"
r-matrix = ">=1.7_3,<2"
r-rcpp = ">=1.1.0,<2"
r-rcpparmadillo = ">=14.4.2_1,<15"
